### PR TITLE
Update recipe to sqlalchemy-utils 0.37.0

### LINKED ISSUE #45: Update to sqlalchemy-utils 0.37.0 for compatibility with SQLAlchemy 1.4
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Following [kvesteri/sqlalchemy-utils issue 507](https://github.com/kvesteri/sqlalchemy-utils/issues/507), this recipe should update sqlalchemy-utils to the new release 0.37.0 to fix the compatibility issue with SQLAlchemy 1.4

<br/>
Environment (<code>conda list</code>):

Any environment with SQLAlchemy 1.4

### PR DESCRIPTION
**Pull request by jarkkorantala**
Update to 0.37.0

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jarkkorantala** [comment]
@conda-forge-admin please rerender

**Comment by jarkkorantala** [comment]
Rerender job above appears to have failed as this package has no source package available in PyPI:
https://pypi.org/project/SQLAlchemy-Utils/#files

Will this be a problem?

**Comment by jarkkorantala** [comment]
> Rerender job above appears to have failed as this package has no source package available in PyPI:
> https://pypi.org/project/SQLAlchemy-Utils/#files
> 
> Will this be a problem?

Changed the package to use the wheel, which seems to work.

**Comment by igortg** [comment]
Let's go with that and hope that https://github.com/kvesteri/sqlalchemy-utils/issues/512 to be solved in the next release

**Pull request merged**
